# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2025-present ntool project and contributors.

# Rust code style format configurations.

# Control the maximum width of a line.
max_width = 80

# Control the number of spaces for indentation.
tab_spaces = 4

# Control the indentation style.
# Use spaces for indentation instead of hard tabs.
hard_tabs = false